gpu:
  # Optional: Specify CUDA toolkit path if auto-detection fails
  # Examples:
  #   Windows: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8"
  #   Linux: "/usr/local/cuda-11.8"
  cuda_toolkit_path: null
miner:
  api_url: https://mine.defensio.io/api
wallet:
  consolidate_address: null
  # Number of wallets to pre-generate per GPU, more wallets will be generated on demand
  wallets_per_gpu: 10
